# Generated by Django 2.1.1 on 2018-09-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0004_property_maps_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='postadd',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='direction',
        ),
        migrations.AddField(
            model_name='property',
            name='bath',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='typ',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
